"""Shared constants for PiBot."""

PIBOT_PREFIX = "пибот "
PIBOT_PREFIX_LEN = len(PIBOT_PREFIX)

RANK_OWNER = 1
RANK_ADMIN_PLUS = 2
RANK_ADMIN = 3
RANK_MEMBER = 4

MAX_TRACKED_MESSAGES = 200
GROUP_HISTORY_MAX = 200
PRIVATE_HISTORY_MAX = 100
HISTORY_MAX_CHATS = 200
HISTORY_TTL = 1800  # 30 minutes
HISTORY_TOKEN_BUDGET = 3000

AI_MAX_HISTORY = 20
AI_RETRY_MAX_ATTEMPTS = 3
AI_RETRY_BASE_DELAY = 1.0
GROQ_MODEL = "llama-3.3-70b-versatile"
# Чатгпт бесплатный - openai/gpt-oss-20b:free
OPENROUTER_MODEL = "poolside/laguna-s-2.1:free"

DELETE_BATCH_SIZE = 100
MAX_MESSAGE_AGE = 120

TRIGGER_SPAM_WINDOW = 10
TRIGGER_SPAM_LIMIT = 5
TRIGGER_SPAM_MUTE = 60

ANTISPAM_WINDOW = 1.0
ANTISPAM_MSG_LIMIT = 5
ANTISPAM_MUTE_THRESHOLD = 9
ANTISPAM_MUTE_DURATION = 60
ANTISPAM_MAX_MESSAGE_AGE = 180  # 3 minutes

FILTER_MUTE_DURATION = 60

RANDOM_REPLY_CHANCE = 0.05  # Шанс рандомного ответа 5%
MIN_RANDOM_MSG_LENGTH = 30  # Мин. длина сообщения для пула рандомных ответов

TELEMETRY_MAX_BYTES = 10 * 1024 * 1024  # 10 MB
TELEMETRY_BACKUP_COUNT = 3
TELEMETRY_WRITE_MAX_ATTEMPTS = 3
TELEMETRY_WRITE_BASE_DELAY = 0.5  # exponential backoff: 0.5s, 1s, 2s

MAX_MESSAGE_LENGTH = 4096  # Telegram hard limit per message

MAX_COMMAND_ARG_LENGTH = 200  # params length limit for admin commands
MAX_WRITE_TEXT_LENGTH = 4096  # text length limit for "пибот напиши"
